app/models.py
from flask import current_app, request, url_for
from flask_login import UserMixin, AnonymousUserMixin
from . import db, login_manager

from werkzeug.security import generate_password_hash, check_password_hash


class Permission:
    VISITOR = 1
    READ = 2
    WRITE = 4
    MODERATE = 8
    ADMIN = 16


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role')

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permissions is None:
            self.permissions = 0

    @staticmethod
    def insert_roles():
        roles = {
            'User': [Permission.VISITOR, Permission.READ, Permission.WRITE],
            'Moderator': [Permission.VISITOR, Permission.READ,
                          Permission.WRITE, Permission.MODERATE],
            'Administrator': [Permission.VISITOR, Permission.READ,
                              Permission.WRITE, Permission.MODERATE,
                              Permission.ADMIN],
        }
        default_role = 'User'
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.reset_permissions()
            for perm in roles[r]:
                role.add_permission(perm)
            role.default = (role.name == default_role)
            db.session.add(role)
        db.session.commit()

    def add_permission(self, perm):
        if not self.has_permission(perm):
            self.permissions += perm

    def remove_permission(self, perm):
        if self.has_permission(perm):
            self.permissions -= perm

    def reset_permissions(self):
        self.permissions = 0

    def has_permission(self, perm):
        return self.permissions & perm == perm

    def __repr__(self):                 # pragma: no cover
        return '<Role %r>' % self.name  # pragma: no cover


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    def __repr__(self):                     # pragma: no cover
        return '<User %r>' % self.username  # pragma: no cover

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['ADMIN_EMAIL']:
                self.role = Role.query.filter_by(name='Administrator').first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def can(self, perm):
        return self.role is not None and self.role.has_permission(perm)

    def is_administrator(self):
        return self.can(Permission.ADMIN)

    def is_supervisor(self):
        return self.can(Permission.ADMIN)



class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False

    def is_moderator(self):
        return self.can(Permission.ADMIN)


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_debugtoolbar import DebugToolbarExtension
from flask_login import LoginManager
from .admin import Admin, SecuredHomeView


from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
toolbar = DebugToolbarExtension()
admin = Admin(
    template_mode='bootstrap4',
    base_template='/admin/new_master.html')
login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config.get(config_name)) or config['default']

    bootstrap.init_app(app)
    toolbar.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    admin.init_app(app, index_view=SecuredHomeView())

    from app import blueprints
    blueprints.init_app(app)

    return app

app/blueprints.py
from .main import main as main_blueprint
from .auth import auth as auth_blueprint
from .models import User, Role
from app import db


def init_app(app):
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from app import admin
    if len(admin._views) == 1:  # Secure blueprints for app testing
        admin.add_model_views([
            User, Role
        ], db)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors  # nopep8
from ..models import Permission  # nopep8


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from flask import render_template, redirect, url_for, abort
from . import main

from flask_login import current_user


@main.route('/', methods=['GET', 'POST'])
def index():
    # if form.validate_on_submit():
    #     return redirect(url_for('.index'))
    return render_template('index.html')


@main.route('/internal', methods=['GET', 'POST'])
def internal():
    abort(500)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Boilerplate{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
{% endblock %}

{% block navbar %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarToggler">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Boilerplate</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-right">
                    {% if current_user.is_administrator() %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.index') }}">Admin</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        {% else %}
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% endblock %}

{% block content %}
<div class="container" id="index">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Boilerplate{% endblock %}

{% block page_content %}
<div class="container">
    <div class="page-header">
        <div class="card">
            <div class="card-body">
                {% if current_user.username %}
                <h1>Hello {{ current_user.username }}</h1>
                {% else %}
                <h1>Hello Stranger!</h1>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/supervisor/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Boilerplate{% endblock %}

{% block page_content %}
<div class="container">
    <div class="page-header">
        <div class="card">
            <div class="card-body">
                <h1>Rapports</h1>
            </div>
        </div>
    </div>
</div>
{% endblock %}